site_name: CCPacks Documentation

nav:
    - Home: index.md
    - Pack Installation: pack_installation.md
    - Pack Structure: pack_structure.md
    - CCPacks:
        - Custom Content:
            - Blocks: 
                - General: block/general.md
                - Falling Blocks: block/falling_block.md
                - Stairs: block/stairs.md
                - Slabs: block/slabs.md
            - Items:
                - Armor: item/armor.md
                - Durable Item: item/durable.md
                - Food: item/food.md
                - General: item/general.md
                - Tools: item/tools.md
                - Weapons: item/weapons.md
                - Discs: item/disc.md
            - Entities (WIP):
                - Chicken: chicken.md
                - Cow: cow.md
                - Pig: pig.md
                - Sheep: sheep.md
            - Universal Powers: universal_powers.md
            - Status Effects: effect.md
            - Enchantments: enchantment.md
            - Portal: portal.md
            - Keybind: keybind.md
            - Particle: particle.md
            - Sound Event: sound_event.md
        - Actions:
            - Item Actions:
                - Remove Durability: item_actions/remove_durability.md
                - Change Name: item_actions/change_name.md
            - Entity Actions:
                - Crafting GUI: entity_actions/crafting_gui.md
                - Block Raycast: entity_actions/raycast_block.md
        - Conditions:
            - Item Conditions:
                - Compare Durability: item_conditions/compare_durability.md
                - Compare Amount: item_conditions/compare_amount.md
    - Apoli:
        - Types:
            - Power Types: apoli/power_types.md
            - Data Types: apoli/data_types.md
            - Power JSON: apoli/power_json.md
        - Conditions:
            - Biome Conditions: apoli/biome_conditions.md
            - Block Conditions: apoli/block_conditions.md
            - Damage Conditions: apoli/damage_conditions.md
            - Entity Conditions: apoli/entity_conditions.md
            - Fluid Conditions: apoli/fluid_conditions.md
            - Item Conditions: apoli/item_conditions.md
            - Meta Conditions: apoli/meta_conditions.md
        - Actions:
            - Block Actions: apoli/block_actions.md
            - Entity Actions: apoli/entity_actions.md
            - Item Actions: apoli/item_actions.md
            - Meta Actions: apoli/meta_actions.md
        - Miscellaneous:
            - Vanilla Damage Sources: apoli/misc/vanilla_damage_sources.md

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

separator: '_'
plugins:
  - search
  - mermaid2:
      version: 8.6.4
      arguments:
          theme: 'neutral'
      
extra_javascript:
    - https://unpkg.com/mermaid@8.7.0/dist/mermaid.min.js